import type { StaticImageData } from "next/image";

import jantar from "../../../public/images/jantar.jpg";
import passagens from "../../../public/images/passagens-lua-de-mel.png";
import hospedagem from "../../../public/images/hospedagem-lua-de-mel.png";
import passeio from "../../../public/images/passeio-lua-de-mel.png";
import mudanca from "../../../public/images/mudanca-novo-lar.png";
import vinhosQueijo from "../../../public/images/vinhosqueijo.jpg";
import grillPhilco from "../../../public/images/grill-philco.png";
import grillMondial from "../../../public/images/grill-mondial.png";
import kitCadenceCozinha from "../../../public/images/kit-cadence-cozinha.png";
import jogoJantarPearl from "../../../public/images/jogo-jantar-pearl.png";
import pratoBoloCoracao from "../../../public/images/prato-bolo-coracao.png";
import rechaudOvalDynasty from "../../../public/images/rechaud-oval-dynasty.png";
import wolffXicarasPearl from "../../../public/images/wolff-xicaras-pearl.png";

export type GiftImageSource = StaticImageData | string;

export interface IBaseGift {
  id: string;
  titulo: string;
  descricao: string;
  valor: string;
  foto: GiftImageSource;
}

export interface IPixGift extends IBaseGift {
  type: "pix";
  pix: string;
}

export interface IPhysicalGift extends IBaseGift {
  type: "physical";
  storeName: string;
  link: string;
}

export type IGift = IPixGift | IPhysicalGift;

const pix =
  "00020126360014br.gov.bcb.pix0114+55379919915985204000053039865802BR5923RAFAELA_AMARAL_DA_SILVA6005Moema610935604-00062290525A4LN261781111784046517539630414CD";

export const pixGifts: IPixGift[] = [
  {
    id: "pix-cafe-manha",
    type: "pix",
    titulo: "Café da Manhã Especial",
    descricao: "Um momento leve e gostoso para aproveitarmos juntos depois do casamento.",
    valor: "R$ 250",
    foto: vinhosQueijo,
    pix,
  },
  {
    id: "pix-jantar",
    type: "pix",
    titulo: "Jantar na Lua de Mel",
    descricao: "Um jantar especial para celebrarmos essa nova etapa juntos.",
    valor: "R$ 700",
    foto: jantar,
    pix,
  },
  {
    id: "pix-sobremesa-romantica",
    type: "pix",
    titulo: "Uma Sobremesa Romântica",
    descricao: "Uma sobremesa deliciosa para adoçarmos nossos primeiros momentos como casal.",
    valor: "R$ 100",
    foto: "https://images.unsplash.com/photo-1551024506-0bccd828d307?fm=jpg&q=80&w=900&auto=format&fit=crop",
    pix,
  },
  {
    id: "pix-passagens",
    type: "pix",
    titulo: "Passagens para a Lua de Mel",
    descricao: "Contribuição para as passagens da nossa primeira viagem como casados.",
    valor: "R$ 800",
    foto: passagens,
    pix,
  },
  {
    id: "pix-jantar-romantico",
    type: "pix",
    titulo: "Jantar Romântico à Luz de Velas",
    descricao: "Um jantar à luz de velas para celebrarmos essa nova fase com todo romantismo.",
    valor: "R$ 300",
    foto: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?fm=jpg&q=80&w=900&auto=format&fit=crop",
    pix,
  },
  {
    id: "pix-mudanca",
    type: "pix",
    titulo: "Cota para a Mudança",
    descricao: "Contribuição para organizarmos a mudança para o nosso novo lar.",
    valor: "R$ 500",
    foto: mudanca,
    pix,
  },
  {
    id: "pix-piquenique-dois",
    type: "pix",
    titulo: "Um Piquenique a Dois",
    descricao: "Um piquenique romântico para aproveitarmos um momento especial juntos.",
    valor: "R$ 150",
    foto: "https://images.unsplash.com/photo-1549934159-af720506e2bb?fm=jpg&q=80&w=900&auto=format&fit=crop",
    pix,
  },
  {
    id: "pix-passeio",
    type: "pix",
    titulo: "Passeio na Lua de Mel",
    descricao: "Uma experiência especial para conhecermos o destino da nossa viagem.",
    valor: "R$ 650",
    foto: passeio,
    pix,
  },
  {
    id: "pix-passeio-por-do-sol",
    type: "pix",
    titulo: "Um Passeio ao Pôr do Sol",
    descricao: "Um passeio inesquecível para admirarmos o pôr do sol como recém-casados.",
    valor: "R$ 200",
    foto: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?fm=jpg&q=80&w=900&auto=format&fit=crop",
    pix,
  },
  {
    id: "pix-hospedagem",
    type: "pix",
    titulo: "Hospedagem da Lua de Mel",
    descricao: "Uma diária para aproveitarmos a lua de mel com tranquilidade.",
    valor: "R$ 750",
    foto: hospedagem,
    pix,
  },
];

export const physicalGifts: IPhysicalGift[] = [
  {
    id: "fisico-forno-embutir-philco",
    type: "physical",
    titulo: "Forno de Embutir Elétrico 46 Litros Philco",
    descricao: "Forno elétrico de embutir Philco, 46 litros, com funções de assar, gratinar, grelhar e dourar.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/forno-de-embutir-eletrico-46-litros-philco/techshop/frnphc00042a/6670c77049ffdb0b51233daf710cdffc.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/forno-de-embutir-eletrico-46-litros-philco/p/aaa3a1d2ck/ed/frne/",
  },
  {
    id: "fisico-coifa-oster",
    type: "physical",
    titulo: "Coifa de Parede Oster Inox Touch Control 90cm",
    descricao: "Coifa de parede Oster em inox, 90 cm, com painel touch control e iluminação em LED.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/coifa-de-parede-oster-inox-touch-control-90cm/osteroficial/12640/885e9fe48f809a0a8d5c8f18a61cadc4.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/coifa-de-parede-oster-inox-touch-control-90cm/p/bae0h6gf74/ed/copa/",
  },
   {
    id: "fisico-cooktop-eletrico-philco-volcano",
    type: "physical",
    titulo: "Cooktop Elétrico 5 Bocas Philco Volcano 8400W",
    descricao: "Cooktop elétrico Philco Volcano, vitrocerâmico, 5 bocas, 8400W, com painel touch e timer.",
    valor: "Presente físico",
    foto: "https://i.promobit.com.br/static/p/168/542484415816933505857002743548.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/cooktop-eletrico-5-bocas-philco-volcano-8400w-pct55vc/p/djd2f2hed1/ed/ck5b/",
  },
  {
    id: "fisico-panela-brinox-vanilla",
    type: "physical",
    titulo: "Jogo de Panelas Brinox Ceramic Life 8 Peças",
    descricao: "Jogo de panelas antiaderente cerâmico Brinox Smart Plus, cor Vanilla, 8 peças.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/jogo-de-panelas-brinox-antiaderente-ceramic-life-8-pecas-smart-plus-vanilla/mimorada/15906472915/791e2040f3b7111dde885890704bc748.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-panelas-brinox-antiaderente-ceramic-life-8-pecas-smart-plus-vanilla/p/bbe334600a/ud/cjpn/",
  },
  {
    id: "fisico-panela-mimo-style",
    type: "physical",
    titulo: "Jogo de Panelas 17 Peças Premium Indução",
    descricao: "Jogo de panelas Mimo Style com revestimento cerâmico antiaderente de 4mm, compatível com indução.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/jogo-de-panelas-17-pecas-premium-inducao-revestimento-ceramico-antiaderente-4mm-mimo-style/feherosshop/15104909877/d53507b9c2db0e94939a5db135151f4b.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-panelas-17-pecas-premium-inducao-revestimento-ceramico-antiaderente-4mm-mimo-style/p/ag3dc78ead/ud/cjpn/",
  },
  {
    id: "fisico-multiprocessador-philco",
    type: "physical",
    titulo: "Multiprocessador Philco 1000W 5 em 1",
    descricao: "Multiprocessador Philco PMP10A, 1000W, com 5 funções para facilitar o preparo das refeições.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/multiprocessador-philco-1000w-5-em-1-pmp10a/alecolchoesemoveis/44670a283b4011f0b72642010a480899/92fe6a570e355038d81db57b0d3823b5.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/multiprocessador-philco-1000w-5-em-1-pmp10a/p/jech634e5h/ep/prsa/",
  },
  {
    id: "fisico-purificador-electrolux",
    type: "physical",
    titulo: "Purificador de Água Electrolux Compacto",
    descricao: "Purificador Electrolux eletrônico, painel digital, bivolt, para água natural, fria ou gelada.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/purificador-electrolux-eletronico-compacto-efficient-painel-digital-bivolt-cinza-pe11x/electrolux/2002605/182a853ba54e20cd1852627202d325ab.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/purificador-electrolux-eletronico-compacto-efficient-painel-digital-bivolt-cinza-pe11x/p/714958200/ep/papd/",
  },
  {
    id: "fisico-jantar-pomerode",
    type: "physical",
    titulo: "Aparelho de Jantar 42 Peças Pomerode",
    descricao: "Aparelho de jantar Schmidt em porcelana, 42 peças, para recebermos família e amigos.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/aparelho-de-jantar-42-pecas-pomerode-schmidt/lojawebcontinentalmarketplace/mkp001359000161/42f8ca42c2c1bea4014c5e021672f069.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/aparelho-de-jantar-42-pecas-pomerode-schmidt/p/aed12bcdb3/ud/apja/",
  },
  {
    id: "fisico-jantar-ryo-maresia",
    type: "physical",
    titulo: "Aparelho de Jantar 20 Peças Ryo Maresia",
    descricao: "Aparelho de jantar Oxford, coleção Ryo Maresia, 20 peças, em porcelana.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/aparelho-de-jantar-20-pecas-ryo-maresia-oxford/lojawebcontinentalmarketplace/mkp001359002291/eaf0d252b9c1e772db082e693d9cc5a7.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/aparelho-de-jantar-20-pecas-ryo-maresia-oxford/p/gb789h5ebh/ud/apja/",
  },
  {
    id: "fisico-faqueiro-pisa",
    type: "physical",
    titulo: "Faqueiro 30 Peças Aço Inox Pisa Wolff",
    descricao: "Faqueiro Wolff Pisa em aço inox, 30 peças, para até 6 pessoas.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/faqueiro-30-pecas-aco-inox-pisa-wolff-rojemac/fekibeststore/p7625/38c9cc4f4a4574c82dc31af5029ca2db.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/faqueiro-30-pecas-aco-inox-pisa-wolff-rojemac/p/bg21746h43/ud/faqu/",
  },
  {
    id: "fisico-faqueiro-viena",
    type: "physical",
    titulo: "Faqueiro Viena 54 Peças em Inox Wolff",
    descricao: "Faqueiro Wolff Viena em inox, conjunto completo com 54 peças.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/faqueiro-viena-com-54-pecas-em-inox-wolff/lojawebcontinentalmarketplace/mkp005045000370/9aded365feefdc3715c589c3688ac5c4.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/faqueiro-viena-com-54-pecas-em-inox-wolff/p/cd4a5760ag/ud/faqu/",
  },
  {
    id: "fisico-tacas-pearl",
    type: "physical",
    titulo: "Jogo de 12 Taças de Sobremesa Cristal Pearl",
    descricao: "Taças de sobremesa Wolff em cristal, detalhes de bolinhas peroladas, 200ml, kit com 12 unidades.",
    valor: "Presente físico",
    foto: "https://a-static.mlcdn.com.br/470x352/jogo-12-taca-de-sobremesa-cristal-pearl-bolinha-wolff-200ml/lojawebcontinentalmarketplace/mkp005643010574/f13fc7d8a05dab48bf2d88f552324a61.jpeg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-12-taca-de-sobremesa-cristal-pearl-bolinha-wolff-200ml/p/ah4255608c/ud/tcsb/",
  },
  {
    id: "fisico-lavadora-brastemp-14kg",
    type: "physical",
    titulo: "Lavadora de Roupas Brastemp 14kg Cesto Inox",
    descricao: "Lavadora Brastemp 14kg, cesto inox, 12 programas de lavagem, com ciclo tira-manchas e sensor de nível de água.",
    valor: "Presente físico",
    foto: "https://brastemp.vtexassets.com/arquivos/ids/271205-800-auto?v=638997704625270000&width=800&height=auto&aspect=true",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/lavadora-de-roupas-brastemp-14kg-cesto-inox-12-programas-de-lavagem-branca-bwj14abana/p/240738000/ed/lava/",
  },
  {
    id: "fisico-lava-loucas-midea-dwa14s",
    type: "physical",
    titulo: "Lava-Louças Midea Cinza 14 Serviços",
    descricao: "Lava-louças Midea DWA14S, cinza, para até 14 serviços, com 6 programas de lavagem e função adiar início.",
    valor: "Presente físico",
    foto: "https://fastshopbr.vtexassets.com/arquivos/ids/5145984/0_8bc18625-34ae-4de2-931a-f00a345bc8d6.jpeg.jpg?v=639181172775100000",
    storeName: "Magazine Luiza",
    link: "https://m.magazineluiza.com.br/lava-loucas-midea-cinza-com-14-servicos-06-programas-de-lavagem-e-funcao-adiar-inicio-dwa14s/p/jjc3edc1a7/ed/l14s/?partner_id=64853&utm_source=pdp_desk&utm_medium=share&seller_id=fastshop2",
  },
  {
    id: "fisico-aspirador-electrolux-stk12",
    type: "physical",
    titulo: "Aspirador de Pó Portátil e Vertical Electrolux 1100W",
    descricao: "Aspirador Electrolux STK12, 1100W, modelo 2 em 1, com filtro HEPA e cabo elétrico de 5 metros.",
    valor: "Presente físico",
    foto: "https://electrolux.vtexassets.com/arquivos/ids/281863-1000-1000?v=638905372275800000&width=1000&height=1000&aspect=true&format=auto",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/aspirador-de-po-portatil-e-vertical-electrolux-1100w-stk12-preto/p/021499200/ep/apdv/",
  },
  {
    id: "fisico-robo-aspirador-xiaomi-x20-max",
    type: "physical",
    titulo: "Aspirador Robô Xiaomi X20 Max",
    descricao: "Robô aspirador Xiaomi Mi Vacuum X20 Max, preto, com navegação a laser (LDS), sucção de 8000 Pa e compatível com app.",
    valor: "Presente físico",
    foto: "https://s2-techtudo.glbimg.com/5vtNTIof25nM85VyxzumEbcpHOo=/0x0:1915x1436/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2025/d/o/j4yGHtRPWIVAe1vZaLqw/x20max.jpeg",
    storeName: "Mercado Livre",
    link: "https://www.mercadolivre.com.br/aspirador-xiaomi-robo-x20-max-mi-vacumm-preto/p/MLB44235159?pdp_filters=item_id%3AMLB7348291722&matt_tool=38524122&ua=Nnlx0-yxxEN26m2b_VHA9fPRAEofl9idouqFXIdbH399xw4#origin=whatsapp&sid=whatsapp&wid=MLB7348291722",
  },
  {
    id: "fisico-cervejeira-consul-czd12mt",
    type: "physical",
    titulo: "Cervejeira Consul Vertical Titanium 83L Frost Free",
    descricao: "Cervejeira Consul CZD12MT, 83 litros, Frost Free, com 5 níveis de temperatura, iluminação em LED e prateleiras removíveis.",
    valor: "Presente físico",
    foto: "https://consul.vtexassets.com/arquivos/ids/278243-1000-auto/01_Consul_Cervejeira_CZD12MT_Frontal.webp?v=639181934059070000&quality=80",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/cervejeira-consul-czd12mt-vertical-titanium-83l-frost-free/p/241111000/ed/cedo/",
  },
  {
    id: "fisico-xicaras-porcelana-paddy",
    type: "physical",
    titulo: "Conjunto 6 Xícaras de Chá Porcelana Paddy 200ml",
    descricao: "Conjunto com 6 xícaras de chá em porcelana, detalhes dourados e capacidade de 200ml, ideal para receber com elegância.",
    valor: "Presente físico",
    foto: "https://images.tcdn.com.br/img/img_prod/572954/jogo_6_xicaras_200ml_para_cha_de_porcelana_branca_e_dourado_com_pires_paddy_wolff_25113_4057_1_20181031105016.jpg",
    storeName: "Let's Eat It",
    link: "https://letseatit.com.br/products/cj-6-xicaras-de-cha-porcelana-paddy-200ml",
  },
  {
    id: "fisico-tacas-cerveja-nadir-floripa",
    type: "physical",
    titulo: "Jogo de Taças de Vidro para Cerveja 6 Peças 300ml",
    descricao: "Jogo de taças de vidro Nadir Floripa, 6 peças, 300ml, design moderno para servir cervejas com elegância.",
    valor: "Presente físico",
    foto: "https://www.havan.com.br/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/j/o/jogo-de-tacas-6-pecas-floripa-nadir_279299_1.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-tacas-de-vidro-para-cerveja-6-pecas-300ml-nadir-floripa/p/142225300/ud/tccv/",
  },
  {
    id: "fisico-tacas-cristal-vinho-bohemia",
    type: "physical",
    titulo: "Jogo de 6 Taças de Cristal para Vinho Bohemia Xtra 560ml",
    descricao: "Conjunto com 6 taças de cristal Bohemia Xtra, 560ml, design moderno e resistente, livre de metais pesados.",
    valor: "Presente físico",
    foto: "https://spicy.vtexassets.com/arquivos/ids/234514-800-auto?v=638380055721600000&width=800&height=auto&aspect=true",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/kit-jogo-conjunto-6-tacas-de-cristal-para-vinho-drink-bohemia-560ml-xtra-ndi-alta-elegante-resistente-moderna/p/cc466a89gj/ud/taag/",
  },
  {
    id: "fisico-tacas-versalhes-dourada-lehavi",
    type: "physical",
    titulo: "Jogo de 6 Taças Vidro Borda Dourada Versalhes 340ml",
    descricao: "Jogo de taças Lehavi Versalhes, 6 peças, 340ml, em vidro com borda dourada para uma mesa mais sofisticada.",
    valor: "Presente físico",
    foto: "https://marbeldistribuidora.com.br/wp-content/uploads/2024/09/7908613102940_1_20240912094126.png",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-6-tacas-vidro-com-borda-dourada-versalhes-340ml-lehavi/p/aj2d862gk0/ud/udta/",
  },
  {
    id: "fisico-copos-altos-versalhes-lehavi",
    type: "physical",
    titulo: "Jogo de 6 Copos Altos 420ml Borda Dourada Versalhes",
    descricao: "Jogo de copos altos Lehavi Versalhes, 6 peças, 420ml, em vidro com borda dourada, ideal para drinks e refrescos.",
    valor: "Presente físico",
    foto: "https://cdn.awsli.com.br/600x1000/1843/1843438/produto/341189228/7432f27b3ff92de536245bdd8bd0e574-eb0gutwydz.jpg",
    storeName: "Casas Bahia",
    link: "https://www.casasbahia.com.br/jogo-de-6-copos-altos-420ml-borda-dourada-versalhes-lehavi/p/1582226273",
  },
  {
    id: "fisico-copos-haus-concept-pavillion",
    type: "physical",
    titulo: "Jogo de Copos de Vidro 350ml 6 Peças Pavillion",
    descricao: "Jogo de copos de vidro Haus Concept Pavillion, 6 peças, 350ml, multiuso para água, sucos e drinks.",
    valor: "Presente físico",
    foto: "https://img.economizeiro.com/5-2023/5292023115542AM.webp",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-copos-de-vidro-350ml-6-pecas-haus-concept-pavillion/p/231205400/ud/coco/",
  },
  {
    id: "fisico-conjunto-assar-servir-tramontina-cosmos",
    type: "physical",
    titulo: "Conjunto para Assar e Servir Inox 3 Peças Tramontina Cosmos",
    descricao: "Conjunto Tramontina Cosmos em aço inox com tampa de vidro, 3 peças, ideal para assar e servir com elegância.",
    valor: "Presente físico",
    foto: "https://assets.tramontina.com.br/upload/tramon/imagens/FAR/64310114PDM001G.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/conjunto-para-assar-e-servir-inox-3-pecas-tramontina-cosmos-64310114/p/144225500/ud/uccm/",
  },
  {
    id: "fisico-potes-hermeticos-electrolux-10pc",
    type: "physical",
    titulo: "Jogo de Potes de Plástico Hermético Electrolux 10 Peças",
    descricao: "Jogo de potes herméticos Electrolux com tampa, 10 peças, ideal para organizar e conservar alimentos na geladeira ou freezer.",
    valor: "Presente físico",
    foto: "https://i.promobit.com.br/168/726739349815676538441183072759.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-potes-de-plastico-hermetico-electrolux-com-tampa-41029853-10-pecas/p/212738100/ud/poud/",
  },
  {
    id: "fisico-smart-tv-58-philips",
    type: "physical",
    titulo: 'Smart TV 58" 4K UHD LED Philips 58PUG7019/78',
    descricao: "Smart TV Philips 58 polegadas, 4K UHD, com Wi-Fi, Bluetooth, Google Assistente, 3 entradas HDMI e 2 USB.",
    valor: "Presente físico",
    foto: "https://i.promobit.com.br/static/p/168/809600282717290845736318451516.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/smart-tv-58-4k-uhd-led-philips-58pug7019-78-wi-fi-bluetooth-google-assistente-3-hdmi-2-usb/p/238616500/et/elit/",
  },
  {
    id: "fisico-cooktop-gas-electrolux-efficient",
    type: "physical",
    titulo: "Cooktop 5 Bocas a Gás Electrolux Efficient",
    descricao: "Cooktop a gás Electrolux Efficient, mesa de vidro, 5 bocas, grade de aço fosco, com queimadores selados de alta performance.",
    valor: "Presente físico",
    foto: "https://electrolux.vtexassets.com/arquivos/ids/275852-1000-1000?v=638851563816870000&width=1000&height=1000&aspect=true&format=auto",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/cooktop-5-bocas-a-gas-electrolux-mesa-de-vidro-efficient-grade-de-aco-fosco-ke5gr/p/fa8k98k60f/ed/cook/",
  },
  {
    id: "fisico-kit-lixeiras-automaticas-uzy",
    type: "physical",
    titulo: "Kit 2 Lixeiras Automáticas Inteligentes 12L",
    descricao: "Kit com 2 lixeiras automáticas, sensor infravermelho, 12 litros, cor preta, abertura e fechamento sem contato.",
    valor: "Presente físico",
    foto: "https://product-hub-prd.madeiramadeira.com.br/654902589/images/5bc4e3d6-070b-4c9e-b4db-fe9dc1e6eef8e42a799288d4c55af560277980.jpg?width=600&canvas=1:1&bg-color=FFF",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/kit-2-lixeiras-automaticas-inteligentes-12l-sensor-infravermelho-branco-uzy-shop-comercial/p/ak7d1dg7hc/ci/lixi/",
  },
  {
    id: "fisico-grill-philco-pgr21pi",
    type: "physical",
    titulo: "Grill Philco PGR21PI Maxx Clean 2 em 1",
    descricao: "Grill e sanduicheira Philco, retangular, 1000W, antiaderente, com coletor de gordura.",
    valor: "Presente físico",
    foto: grillPhilco,
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/grill-philco-pgr21pi-maxx-clean-2-em-1-retangular-1000w-antiaderente-com-coletor-de-gordura/p/236589900/ep/epgr/",
  },
  {
    id: "fisico-grill-mondial-g03",
    type: "physical",
    titulo: "Grill Mondial G-03 Redondo 1270W",
    descricao: "Grill redondo Mondial Cook & Grill, 1270W, antiaderente, ideal para pizzas e lanches.",
    valor: "Presente físico",
    foto: grillMondial,
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/grill-mondial-g-03-redondo-1270w-antiaderente/p/236676600/ep/epgr/",
  },
  {
    id: "fisico-kit-cadence-cozinha-ideal",
    type: "physical",
    titulo: "Kit Cadence Cozinha Completa Ideal 110V",
    descricao: "Kit Cadence com cafeteira, mixer, liquidificador portátil e chaleira elétrica para o dia a dia na cozinha.",
    valor: "Presente físico",
    foto: kitCadenceCozinha,
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/kit-cadence-cozinha-completa-ideal-110v/p/gfb26df9d6/ep/elkp/",
  },
  {
    id: "fisico-jogo-jantar-pearl-wolff",
    type: "physical",
    titulo: "Jogo de Jantar 20 Peças Pearl Cristal Wolff",
    descricao: "Jogo de jantar Wolff em cristal, linha Pearl com detalhes perolados, 20 peças para servir com elegância.",
    valor: "Presente físico",
    foto: jogoJantarPearl,
    storeName: "WolyCasa",
    link: "https://www.wolycasa.com.br/products/jogo-de-jantar-20-pecas-pearl-cristal-wolff",
  },
  {
    id: "fisico-prato-bolo-coracao-lyor",
    type: "physical",
    titulo: "Prato para Bolo com Pé e Tampa Coração Cristal",
    descricao: "Prato para bolo Lyor em cristal, com pé, tampa em formato de coração, 25,5cm x 29cm.",
    valor: "Presente físico",
    foto: pratoBoloCoracao,
    storeName: "WolyCasa",
    link: "https://www.wolycasa.com.br/products/prato-para-bolo-com-pe-e-tampa-coracao-25-5cm-x-29cm-cristal-lyor",
  },
  {
    id: "fisico-rechaud-oval-dynasty",
    type: "physical",
    titulo: "Rechaud Oval em Porcelana com Queimador 2,3L",
    descricao: "Rechaud oval Dynasty em porcelana, com queimador de 2,3L, ideal para manter pratos aquecidos à mesa.",
    valor: "Presente físico",
    foto: rechaudOvalDynasty,
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/rechaud-oval-em-porcelana-com-queimador-23l-dynasty/p/gchd5hbd8e/ud/rech/",
  },
  {
    id: "fisico-wolff-xicaras-prato-doce",
    type: "physical",
    titulo: "Wolff 4 Xícaras, Prato Doce, Manteigueira e Açucareiro",
    descricao: "Conjunto Wolff em cristal, linha Pearl, com 4 xícaras, prato para doce, manteigueira e açucareiro.",
    valor: "Presente físico",
    foto: wolffXicarasPearl,
    storeName: "Mercado Livre",
    link: "https://www.mercadolivre.com.br/wolff--4-xicaras--prato-doce--mantegueira--acucareiro/up/MLBU3383974968",
  },
  {
    id: "fisico-jogo-toalha-ondas-casa-dona",
    type: "physical",
    titulo: "Jogo de Toalha Ondas 100% Algodão 450g/m² 4 Peças",
    descricao: "Jogo de toalhas Casa Dona, 100% algodão, 450g/m², com 2 toalhas de banho e 2 de rosto.",
    valor: "Presente físico",
    foto: "https://cdn.awsli.com.br/2500x2500/2467/2467495/produto/324779029/toalha-wave-azul-e-branco-ooywbszf72.png",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-toalha-ondas-100-algodao-450g-m2-4-pecas-banho-e-rosto-casa-dona/p/faff079bcd/cm/joto/",
  },
  {
    id: "fisico-jogo-toalhas-karsten-lumina",
    type: "physical",
    titulo: "Jogo de Toalhas Banhão Gigante Karsten Lumina 4 Peças",
    descricao: "Jogo de toalhas Karsten Lumina, fio penteado, com 2 toalhas banhão gigante e 2 de rosto.",
    valor: "Presente físico",
    foto: "https://images.tcdn.com.br/img/img_prod/951952/jogo_de_toalhas_banhao_gigante_lumina_karsten_4_pecas_fio_penteado_431_1_9ca7a9e6317b58ef3e3aba36e1b0ee4d.jpg",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/jogo-de-toalhas-banhao-gigante-karsten-lumina-4-pecas-fio-penteado-emcompre/p/chjbj2h86g/cm/joto/",
  },
  {
    id: "fisico-kit-coberdrom-mr-enxovais",
    type: "physical",
    titulo: "Kit Coberdrom Casal e Queen 5 Peças 400 Fios Dupla Face com Sherpa",
    descricao: "Kit coberdrom MR Enxovais, dupla face com sherpa, 400 fios, casal e queen, 5 peças.",
    valor: "Presente físico",
    foto: "https://images.yampi.me/assets/stores/mr-enxovais/uploads/images/kit-coberdrom-dupla-face-casal-queen-soft-verde-militar-67d8d7fd55d3a-large.png",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/kit-coberdrom-casal-e-queen-5-pecas-400-fios-dupla-face-com-sherpa-mr-enxovais/p/hkdcdbdga4/cm/cobl/",
  },
  {
    id: "fisico-jogo-cama-king-altenburg-ballerina",
    type: "physical",
    titulo: "Jogo de Cama King 4 Peças Altenburg Ballerina",
    descricao: "Jogo de cama Altenburg, linha Ballerina, bordado em cetim, 300 fios, king, 4 peças.",
    valor: "Presente físico",
    foto: "https://altenburg.vtexassets.com/arquivos/ids/164980-800-800?v=639058932888130000&width=800&height=800&aspect=true",
    storeName: "Altenburg",
    link: "https://www.altenburg.com.br/jogo-de-cama-king-4-pecas-altenburg-bordados-em-cetim-300-fios-ballerina/p",
  },
  {
    id: "fisico-tanquinho-colormaq-lcs15",
    type: "physical",
    titulo: "Tanquinho de Lavar Roupas Colormaq 15kg LCS15",
    descricao: "Tanquinho Colormaq LCS15, 15kg, motor de 450W, com timer e 6 programas de lavagem.",
    valor: "Presente físico",
    foto: "https://colormaq.vtexassets.com/arquivos/ids/156814-800-800?v=638907115263730000&width=800&height=800&aspect=true",
    storeName: "Magazine Luiza",
    link: "https://www.magazineluiza.com.br/tanquinho-de-lavar-roupas-colormaq-15kg-lcs15/p/241479100/ed/tank/",
  },
];
